-- from Query History
CREATE OR REPLACE TABLE LINEITEM_SNOWPARK(
    "L_ORDERKEY" BIGINT NOT NULL , 
    "L_PARTKEY" BIGINT NOT NULL , 
    "L_SUPPKEY" BIGINT NOT NULL , 
    "L_LINENUMBER" BIGINT NOT NULL , 
    "L_QUANTITY" NUMBER(12, 2) NOT NULL , 
    "L_EXTENDEDPRICE" NUMBER(12, 2) NOT NULL , 
    "L_DISCOUNT" NUMBER(12, 2) NOT NULL , 
    "L_TAX" NUMBER(12, 2) NOT NULL , 
    "L_RETURNFLAG" STRING(1) NOT NULL , 
    "L_LINESTATUS" STRING(1) NOT NULL , 
    "L_SHIPDATE" DATE NOT NULL , 
    "L_COMMITDATE" DATE NOT NULL , 
    "L_RECEIPTDATE" DATE NOT NULL , 
    "L_SHIPINSTRUCT" STRING(25) NOT NULL , 
    "L_SHIPMODE" STRING(10) NOT NULL , 
    "L_COMMENT" STRING(44) NOT NULL)
AS SELECT * FROM (
    SELECT "L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY",
        "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX", "L_RETURNFLAG", "L_LINESTATUS",
        "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"
    FROM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM)
    GROUP BY "L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY",
        "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX", "L_RETURNFLAG", "L_LINESTATUS",
        "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT");

-- render returned Snowpark DataFrame result on screen
SELECT "L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY",
    "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX", "L_RETURNFLAG", "L_LINESTATUS",
    "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"
FROM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM)
GROUP BY "L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", 
    "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX", "L_RETURNFLAG", "L_LINESTATUS", 
    "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT";
SELECT * FROM TABLE(RESULT_SCAN('01b361d4-0002-4652-0055-cf0700132d16'));