-- run interactively one by one in VSCode or Snowsight
USE SCHEMA IMDB.PUBLIC;

CREATE OR REPLACE VIEW VIEW_TEST_DATASET AS
    SELECT REVIEW, SENTIMENT,
        CASE WHEN (SENTIMENT = 'positive') THEN 1
        ELSE 2 END AS SENTIMENT_FLAG
FROM TEST_DATASET;

SELECT *
FROM VIEW_TEST_DATASET
LIMIT 10;

select *, predict_review(ARRAY_CONSTRUCT(REVIEW, SENTIMENT_FLAG)) as PREDICTED_REVIEW
from VIEW_TEST_DATASET
limit 10;

select *, predict_review_batch(REVIEW) as PREDICTED_REVIEW
from VIEW_TEST_DATASET
limit 10;

create or replace table REVIEW_PREDICTION as
select *, predict_review_batch(REVIEW) as PREDICTED_REVIEW
from VIEW_TEST_DATASET;

SELECT *
FROM REVIEW_PREDICTION
LIMIT 10;

SELECT *
FROM REVIEW_PREDICTION
WHERE SENTIMENT_FLAG <> PREDICTED_REVIEW;
