SELECT *
FROM TEST.PUBLIC.HOUSING
SAMPLE row (10 ROWS);


SELECT approx_count_distinct(*)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
TABLESAMPLE (10);