-- run from a terminal in VSCode: SNOWSQL -c test_conn -f 2-titanic-inferred.sql

CREATE OR REPLACE FILE FORMAT TEST.PUBLIC.CSV_HEADER_PARSE
    TYPE='CSV' PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE TEST.PUBLIC.INT_STAGE
    FILE_FORMAT=TEST.PUBLIC.CSV_HEADER_PARSE;

PUT file://..\..\..\..\.spool\titanic.csv @TEST.PUBLIC.INT_STAGE
    OVERWRITE=true AUTO_COMPRESS=false;

-- (1) INFER_SCHEMA --> show inferred columns in tabular format
SELECT *
FROM TABLE(INFER_SCHEMA(
    LOCATION => '@TEST.PUBLIC.INT_STAGE',
    FILES => 'titanic.csv',
    FILE_FORMAT => 'TEST.PUBLIC.CSV_HEADER_PARSE'));

-- (2) INFER_SCHEMA --> show inferred columns w/ data types
SELECT GENERATE_COLUMN_DESCRIPTION(
    ARRAY_AGG(OBJECT_CONSTRUCT(*)), 'table') AS COLUMNS
FROM TABLE(INFER_SCHEMA(
    LOCATION => '@TEST.PUBLIC.INT_STAGE',
    FILES => 'titanic.csv',
    FILE_FORMAT => 'TEST.PUBLIC.CSV_HEADER_PARSE'));

-- (3) INFER_SCHEMA --> create table directly
CREATE OR REPLACE TABLE TEST.PUBLIC.TITANIC USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION => '@TEST.PUBLIC.INT_STAGE',
        FILES => 'titanic.csv',
        FILE_FORMAT => 'TEST.PUBLIC.CSV_HEADER_PARSE')));

SELECT GET_DDL('TABLE', 'TEST.PUBLIC.TITANIC');

COPY INTO TEST.PUBLIC.TITANIC
FROM @TEST.PUBLIC.INT_STAGE
    FILES=('titanic.csv')
    FILE_FORMAT=(FORMAT_NAME=TEST.PUBLIC.CSV_HEADER_PARSE)
    MATCH_BY_COLUMN_NAME=CASE_SENSITIVE
    FORCE=TRUE;

SELECT *
FROM TEST.PUBLIC.TITANIC
LIMIT 10;

